# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               askkaz
tagline:             'A place for my musings'
description:         'Somewhere to practice writing and talk about my transition from aerospace to software development'
url:                 http://askkaz.com
baseurl:             ''
paginate:            5
paginate_path:       "page:num"
gems:                ['jekyll-paginate']

# About/contact
author:
  name:              Adam Kaczmarek
  url:               https://twitter.com/adamkaz
  email:             me@askkaz.com

# Custom vars
version:             1.0.0
